global:
  scrape_interval: 2s

scrape_configs:
  - job_name: edge_gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["edge_gateway:8000"]

  - job_name: session_manager_1
    metrics_path: /metrics
    static_configs:
      - targets: ["session_manager_1:8001"]

  - job_name: session_manager_2
    metrics_path: /metrics
    static_configs:
      - targets: ["session_manager_2:8001"]

  - job_name: resource_manager
    metrics_path: /metrics
    static_configs:
      - targets: ["resource_manager:8002"]

  - job_name: billing_service
    metrics_path: /metrics
    static_configs:
      - targets: ["billing_service:8003"]

  - job_name: analytics_service
    metrics_path: /metrics
    static_configs:
      - targets: ["analytics_service:8004"]
